// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa1DAEsmuBqy1vafCz8IzteNUnue8OZtE',
    appId: '1:880648692270:web:6772887504298e2dc875bf',
    messagingSenderId: '880648692270',
    projectId: 'yemen-family-project',
    authDomain: 'yemen-family-project.firebaseapp.com',
    storageBucket: 'yemen-family-project.firebasestorage.app',
    measurementId: 'G-8L5LRE4L30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_hygGYHiJkMyaxp3PX2KFOBBF0aGCRM',
    appId: '1:880648692270:android:bca8397f61a7160dc875bf',
    messagingSenderId: '880648692270',
    projectId: 'yemen-family-project',
    storageBucket: 'yemen-family-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCilERUAEvypDwffxJCtUO92cJR9C4S_Q',
    appId: '1:880648692270:ios:2652858679a6718fc875bf',
    messagingSenderId: '880648692270',
    projectId: 'yemen-family-project',
    storageBucket: 'yemen-family-project.firebasestorage.app',
    iosBundleId: 'com.example.homeBusinessMobile',
  );

}